services:
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend/Dockerfile
    command: sh -c "npm install && npm run start"
    restart: always
    volumes:
        - ./backend:/app
        - /app/node_modules
    ports:
      - "8080:3000"
    networks:
      - jingle_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db-data:


networks:
  jingle_network:
    driver: bridge
