services:
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend/Dockerfile
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
    command: sh -c "npm install && npm run start"
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    depends_on:
      - mongodb
    networks:
      - jingle_network

  mongodb:
    container_name: mongo-jingle
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_jingle:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-jingle
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongodb_jingle:

networks:
  jingle_network:
    driver: bridge
