services:
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend/Dockerfile
    command: sh -c "npm install && npm run start"
    restart: always
    volumes:
        - ./backend:/app
        - /app/node_modules
    ports:
      - "8080:3000"
    networks:
      - jingle_network

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/var/data
    working_dir: /var/data
    networks:
      - jingle_network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    networks:
      - jingle_network
    ports:
      - "8081:8081"

volumes:
  db-data:


networks:
  jingle_network:
    driver: bridge
